### PR TITLE
updated deps

### PR DESCRIPTION
**Pull request by source-c**

### CODE REVIEW

**Comment by source-c** [comment]
@niwinz Could you please merge and release this? We just freshen up the project dependencies. Thank you.

**Comment by niwinz** [comment]
I can't it has conflict

**Comment by source-c** [comment]
Hmm.. Sounds strange. Github and local git are OK.
May you please provide more information about the conflict in repo? 

Screen Shot 2019-06-26 at 11 12 26
Screen Shot 2019-06-26 at 11 12 54

**Comment by niwinz** [comment]
Seems like github has some problem rebasing it, but mergin it is ok... Strange... 
Ty

**Pull request merged**
