### PR TITLE
Assets classpath support

### PR DESCRIPTION
**Pull request by mitchelkuijpers**
Will first look for a .catacumba file in the classpath and will
otherwise run without a basedir. As discussed in #23

Also adds a simple websocket example

### CODE REVIEW

**Comment by niwinz** [comment]
Thanks for the great work.

One unque question, that is the license of your code (I have seen a EPL LICENSE file on the example project)?

The catacumba project is licensed under BSD (2-Clause) and personally don't like EPL, so can you confirm that yo are licensing the code under BSD (2-Clause) license?

**Comment by niwinz** [comment]
I have included your commits in the  #25 PR.

The websockets support is broken by some change on the ratpack internals. And I try to fix it together migrate catacumbla to the last ratpack version (that includes great amount of breaking changes) (that not implies breaking changes on catacumba I think).

**Comment by mitchelkuijpers** [comment]
Ow lol that license was not intentional it was a fast ```lein new``` project, I can confirm I license it under  BSD (2-Clause) license

**Comment by mitchelkuijpers** [comment]
Btw if I can help in any way I will be happy to do so. I used to be a Java developer so I don't mind fixing some breaking java stuff..

**Comment by niwinz** [comment]
Great! I have removed the LICENSE file.
I close this PR because your commits are already included (with some improvements) on the #25 pr

**Pull request closed without merging**
